In [1]:
SEED = 20040508

In [2]:
from tests.env.simulator import Environment
import numpy as np
np.random.seed(SEED)

In [3]:
env = Environment()

In [4]:
drone_state, task_state, action_state = env.reset()
drone_state.shape, task_state.shape, action_state.shape, env.action_space.info.shape

((6, 6), (1, 7), (0,), (30, 6))

In [17]:
drone_state, task_state, action_state = env.reset()
print(f"任务数目·无人机数目: {env.action_space.info.shape}")

rewards = 0
times = 0
while True:
    times += 1
    action = np.hstack((action_state, np.random.randint(low=0, high=len(drone_state), size=(len(task_state) - len(action_state),))))
    assert len(action) == len(task_state)
    next_drone_state, next_task_state, next_action_state, reward, done, r= env.step(action=action)
    assert np.array_equal(action, next_action_state)
    rewards += reward
    if done:
        break
    drone_state, task_state, action_state = next_drone_state, next_task_state, next_action_state
print(
    f'推送次数{times}\n' +
    '\t' + '\n\t'.join([f'任务{j} -> 无人机{i}' for j, i in enumerate(action_state)])
)

任务数目·无人机数目: (30, 6)
推送次数8
	任务0 -> 无人机3
	任务1 -> 无人机1
	任务2 -> 无人机2
	任务3 -> 无人机5
	任务4 -> 无人机2
	任务5 -> 无人机3
	任务6 -> 无人机0
	任务7 -> 无人机5
	任务8 -> 无人机3
	任务9 -> 无人机2
	任务10 -> 无人机5
	任务11 -> 无人机1
	任务12 -> 无人机3
	任务13 -> 无人机0
	任务14 -> 无人机3
	任务15 -> 无人机0
	任务16 -> 无人机3
	任务17 -> 无人机3
	任务18 -> 无人机2
	任务19 -> 无人机0
	任务20 -> 无人机0
	任务21 -> 无人机2
	任务22 -> 无人机4
	任务23 -> 无人机1
	任务24 -> 无人机1
	任务25 -> 无人机1
	任务26 -> 无人机1
	任务27 -> 无人机5
	任务28 -> 无人机2


In [18]:
from tests.agent import Agent

In [19]:
agent: Agent = Agent(variant="111")
assert agent


In [20]:
drone_state, task_state, action_state = env.reset()
assert action_state.size == 0
print(f"任务数目·无人机数目: {env.action_space.info.shape}")

rewards = 0
times = 0
while True:
    times += 1
    q, action = agent.act(drone_state=drone_state, task_state=task_state, action_state=action_state)
    assert np.array_equal(action[:len(action_state)], action_state)
    
    next_drone_state, next_task_state, next_action_state, reward, done, r = env.step(action=action)
    assert np.array_equal(next_action_state, action)
    assert np.array_equal(next_task_state[:len(task_state)], task_state)

    drone_state, task_state, action_state = next_drone_state, next_task_state, next_action_state
    
    rewards += reward

    if done:
        break
print(
    f'推送次数{times}\n' +
    '\t' + '\n\t'.join([f'任务{j} -> 无人机{i}' for j, i in enumerate(action_state)])
)

任务数目·无人机数目: (20, 4)
推送次数8
	任务0 -> 无人机2
	任务1 -> 无人机2
	任务2 -> 无人机2
	任务3 -> 无人机2
	任务4 -> 无人机2
	任务5 -> 无人机2
	任务6 -> 无人机2
	任务7 -> 无人机2
	任务8 -> 无人机2
	任务9 -> 无人机2
	任务10 -> 无人机2
	任务11 -> 无人机2
	任务12 -> 无人机2
	任务13 -> 无人机2
	任务14 -> 无人机2
	任务15 -> 无人机2
	任务16 -> 无人机2
	任务17 -> 无人机2
	任务18 -> 无人机2
	任务19 -> 无人机2


In [21]:
from pathlib import Path

In [22]:
main_agent = Agent.loads(from_path=Path('output0/main/4-0.7500/full'))
main_agent.variant

'111'

In [23]:
drone_state, task_state, action_state = env.reset()
print(f"任务数目·无人机数目: {env.action_space.info.shape}")
assert action_state.size == 0

rewards = 0
times = 0
while True:
    times += 1
    q, action = main_agent.act(drone_state=drone_state, task_state=task_state, action_state=action_state)
    assert np.array_equal(action[:len(action_state)], action_state)

    next_drone_state, next_task_state, next_action_state, reward, done, r = env.step(action=action)
    assert np.array_equal(next_action_state, action)
    assert np.array_equal(next_task_state[:len(task_state)], task_state)

    drone_state, task_state, action_state = next_drone_state, next_task_state, next_action_state
    
    rewards += reward

    if done:
        break
print(
    f'推送次数{times}\n' +
    '\t' + '\n\t'.join([f'任务{j} -> 无人机{i}' for j, i in enumerate(action_state)]) + '\n' +
    f'最终奖励: {rewards}\n'
)

任务数目·无人机数目: (25, 5)
推送次数6
	任务0 -> 无人机4
	任务1 -> 无人机1
	任务2 -> 无人机0
	任务3 -> 无人机1
	任务4 -> 无人机0
	任务5 -> 无人机3
	任务6 -> 无人机2
	任务7 -> 无人机2
	任务8 -> 无人机4
	任务9 -> 无人机0
	任务10 -> 无人机3
	任务11 -> 无人机2
	任务12 -> 无人机2
	任务13 -> 无人机1
	任务14 -> 无人机3
	任务15 -> 无人机3
	任务16 -> 无人机2
	任务17 -> 无人机4
	任务18 -> 无人机0
	任务19 -> 无人机4
	任务20 -> 无人机1
	任务21 -> 无人机4
	任务22 -> 无人机4
	任务23 -> 无人机4
	任务24 -> 无人机4
最终奖励: 31.79860456770497



In [24]:
drone_state

array([[ 1.        ,  1.        ,  1.        ,  2.01790756,  2.47819382,
        13.86389903],
       [ 1.        ,  0.        ,  1.        ,  2.79551375,  1.92799733,
        13.69191058],
       [ 0.        ,  1.        ,  0.        ,  1.11989786,  0.12061396,
         9.9815033 ],
       [ 0.        ,  1.        ,  0.        ,  0.97932264,  2.05935175,
        10.01028016],
       [ 0.        ,  1.        ,  0.        ,  1.97577883,  1.40486225,
         9.4682261 ]])

In [25]:
task_state

array([[ 0.        ,  1.        ,  0.        ,  8.18914543, -1.74370223,
         2.96292322, 24.03845996],
       [ 0.        ,  0.        ,  1.        ,  5.57083669,  0.36296114,
         2.41704243, 14.45453621],
       [ 1.        ,  0.        ,  0.        ,  4.42226472,  2.2063253 ,
         2.78439625, 12.57804159],
       [ 1.        ,  0.        ,  0.        ,  8.03264291,  5.34726091,
         2.09930514, 10.30415362],
       [ 0.        ,  0.        ,  1.        ,  5.088093  ,  3.24745837,
         2.71899054, 17.25759393],
       [ 0.        ,  1.        ,  0.        ,  8.93512899,  4.55736597,
         2.54862017, 14.04185467],
       [ 0.        ,  0.        ,  1.        ,  6.26149655,  5.21432091,
         2.51318369,  7.49238102],
       [ 0.        ,  0.        ,  1.        , 10.87006444,  2.28913525,
         2.92955722, 10.09780236],
       [ 0.        ,  0.        ,  1.        , 11.02236608,  4.20704684,
         2.76532919, 21.0131444 ],
       [ 0.        ,  1.    

In [26]:
action_state

array([4, 1, 0, 1, 0, 3, 2, 2, 4, 0, 3, 2, 2, 1, 3, 3, 2, 4, 0, 4, 1, 4,
       4, 4, 4])

In [27]:
env.action_space.info

array([[0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

In [1]:
from utils.tools import avg_length

In [2]:
avg_length(avg_tasks_per=100)

12.252345647714384